apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-kjufmuul
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/quay_xjiang/go-kjufmuul:dee3fac6421825e9de9d9d939adfc63f81f95561@sha256:f7d307f9896d82880afc66afc2208e5f2e52ce5ae99eb39a30bacad9c293f0e9
          name: container-image
